name: Deploy Laravel 11 Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo_mysql
          ini-values: |
            memory_limit=1G
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --no-progress --prefer-dist --optimize-autoloader

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy application via rsync
        run: |
          rsync -avz --delete \
          -e "ssh -p ${{ secrets.DIGITALOCEAN_PORT }}" \
          ./ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.REMOTE_DIR }}
