name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
      run: |
        if [ -z "$SSH_PRIVATE_KEY" ]; then
          echo "Error: SSH_PRIVATE_KEY is not set." >&2
          exit 1
        fi
        if [ -z "$HOST" ]; then
          echo "Error: DIGITALOCEAN_HOST is not set." >&2
          exit 1
        fi

        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Verify known hosts setup
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts

    - name: Verify SSH connection
      env:
        USER: ${{ secrets.DIGITALOCEAN_USER }}
        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        PORT: ${{ secrets.DIGITALOCEAN_PORT }}
      run: |
        ssh -o StrictHostKeyChecking=no -p $PORT $USER@$HOST "echo 'SSH connection successful!'"

    - name: Deploy files to DigitalOcean
      env:
        USER: ${{ secrets.DIGITALOCEAN_USER }}
        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        PORT: ${{ secrets.DIGITALOCEAN_PORT }}
        REMOTE_DIR: ${{ secrets.DIGITALOCEAN_REMOTE_DIR_SD }}
      run: |
        rsync -avz -e "ssh -p $PORT" ./ $USER@$HOST:$REMOTE_DIR
